### ISSUE TITLE
Detect adb if it's in PATH

### ISSUE THREAD

**Issue by tuarrep** [SecTheTech/AMDH#14]
My adb bin is in `/home/nicolas/Android/Sdk/platform-tools/adb` but it's resolved by my Linux PATH.

If I run the script, it search for `/usr/bin/adb` by default, I need to provide it manually through `-a`.

It'll great to have it resolved automatically by using the `PATH` env var

**Comment by A-YATTA** [comment]
Replacing the value of the variable "adb_path" in config.py with only `adb` instead of  `/usr/bin/adb`  or `/absolute/path/to/adb`will use the `PATH` env var.

**Comment by tuarrep** [comment]
Could it be the default?

**Comment by A-YATTA** [comment]
Done in the commit [df02fd5](https://github.com/SecTheTech/AMDH/commit/df02fd5b1009a10e8e32b3dc6c433a3948c0c4ca). I  renamed the variable `adb_path` to `adb_binary` (more explicit). 

I will close the issue, you can reopen it if needed.
