### ISSUE TITLE
Unable to specify ADB file directory

### ISSUE THREAD

**Issue by Tar2ed** [SecTheTech/AMDH#33]
Hi SecTheTech,

I just saw that the issue was closed and that there was not any description. I had written something but it seems like it didn't pick it up. I apologise for that. 

So. My issue is that I am unable to specify the ADB file directory to be able to run a scan on my phone. 

The first thing I did was to copy ADB into the AMDH folder so that the script would be able to detect ADB. It didn't work. So I changed tired changing the path, but still didn't work. Even installing Android Studio to get the right path to ADB. 

I don't seem to understand what is the format I need to write the path into **main.py**. 

This should have worked as I have Android Studio now and have confirmed that running this command does lend me right to the ADB path.

**"%LOCALAPPDATA%/Android/Sdk/platform-tools/adb"**

Could you assist me, please?

Thanks.

**Comment by SecTheTech** [comment]
Hi Tar2ed, 
The issue was not appropriate that's why I close it.
As described in the README you have to specify the ADB path using `-a` argument or by editing the file config/main.py.

**Comment by Tar2ed** [comment]
Hi SecTheTech,

Thank you for your fast response. 

I do understand that I need to edit the config.py file. But still when I try and run it it cannot find the specified file. 

What is the structure to specify the path? 

I tried: C:\Users\"Myusername"\AppData\Local\Android\Sdk\platform-tools\adb

![cannot_find_file](https://user-images.githubusercontent.com/44437483/103773806-8d527180-5023-11eb-96b9-a216425bd1a9.PNG)
 
Thank you.
Tar2ed

**Comment by SecTheTech** [comment]
Can you please describe all the steps that you followed

**Comment by Tar2ed** [comment]
Sure I can. 

1. Downloaded Python 3.9.1 and installed it on my computer. 
2. Opened command promt.
3. Ran the command "pip install androguard pwntools"
4. Installed git on my computer. 
5. Ran the command "git clone https://github.com/SecTheTech/AMDH.git"
6. Downloaded Android Studio with ADB included
6. Opened a new command prompt.
7. Ran the command "cd AMDH"  
8. Ran the command "python amdh.py -sA"

That's it. I did not connect my phone yet. 

Thanks.
Tar2ed

**Comment by SecTheTech** [comment]
- Before the step 9 you have to connect your phone with USB cable and enable USB debugging on the phone ([how to enable USB debugging](https://docs.kony.com/konylibrary/visualizer/visualizer_user_guide/content/AndroidUSBDebugging_Windows10.htm)) 
- Before running the amdh.py make sure that your device is connected and your computer is trusted by the phone, then run:
```
adb devices
```
the command should output that something like:
```
List of devices attached
Zhfs74bda   device
```
if instead of device you have unauthorized that mean you have not trusted the computer on the phone.
- Once you have your device connected to the phone then you can run (while keeping your phone plugged to your computer):
```
python amdh.py -sA -a C:\Users\ "username"\AppData\Local\Android\Sdk\platform-tools\adb
```
Let me know if that work.

**Comment by Tar2ed** [comment]
Yep!! It does work. Well only partially. 

It founds the device. And ADB is found. But nothing happens after that. No scan.

That is strange. I ran command prompt in admin mode. 

![Capture](https://user-images.githubusercontent.com/44437483/103782031-e1168800-502e-11eb-9d39-1b14b7258df7.PNG)

**Comment by SecTheTech** [comment]
You are right, the README need to be updated. After adding the support for multi devices there is no output anymore on the console but there is a generated report `<ID_Device>_report.json` for each device. 
I will update the README soon.

**Comment by Tar2ed** [comment]
Ok. So, how will I know if my device has been hardened? I use a OnePlus phone is that helps.

Thanks.
Tar2ed

**Comment by SecTheTech** [comment]
Glad it works! I will close the issue and you can reopen it if needed! 
Thanks for your interest.
